#nacos:
#  config:
#    server-addr: localhost:8848
server:
  port: 8081
spring:
  #数据库连接配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/chat?characterEncoding=utf-8&useSSL=false
    username: root
    password: 20040105

    druid:
      initialSize: 5
      minIdle: 1
      maxActive: 50
      max-wait: 600000
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: false
      maxPoolPreparedStatementPerConnectionSize: 20
      filters: stat,wall
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      useGlobalDataSourceStat: true
  web:
    resources:
      static-locations: classpath:/static/


#mybatis的相关配置
mybatis:
  #mapper配置文件
  mapper-locations: classpath:chat/mapper/*.xml
  type-aliases-package: com.wbh.testsecurity.chat.entity
  #开启驼峰命名
  configuration:
    map-underscore-to-camel-case: true
name: wbh

